databases:
  - name: prometei-db       # Назва бази даних
    plan: free             # План (free для початку)
    databaseName: prometei   # Ім'я БД всередині Postgres
    user: prometei_user    # Користувач БД

services:
  - type: web
    plan: free             # План (free для початку)
    name: prometei-web     # Назва веб-сервісу
    runtime: python
    buildCommand: "./build.sh" # Команда збірки
    # Команда запуску для ASGI (зміни config.asgi:application якщо потрібно)
    startCommand: "gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prometei-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true    # Render згенерує ключ
      - key: WEB_CONCURRENCY # Кількість Gunicorn воркерів
        value: 4
      - key: PYTHON_VERSION
        value: 3.13.3          # Змінено на повну версію 