# Generated by Django 5.2 on 2025-05-01 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Імʼя')),
                ('contact_method', models.CharField(help_text='Email або Telegram', max_length=100, verbose_name='Контактний метод')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('request_type', models.CharField(choices=[('contact', 'Контактна форма'), ('builder', 'Конструктор сайту'), ('promin', 'Заявка Промінь')], default='contact', max_length=20, verbose_name='Тип запиту')),
                ('builder_site_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип сайту')),
                ('builder_modules', models.TextField(blank=True, null=True, verbose_name='Обрані модулі')),
                ('builder_design', models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип дизайну')),
                ('builder_pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість сторінок')),
                ('builder_package', models.CharField(blank=True, max_length=20, null=True, verbose_name='Розрахований пакет')),
                ('builder_price', models.CharField(blank=True, max_length=20, null=True, verbose_name='Орієнтовна ціна')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва проєкту')),
                ('project_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип проєкту')),
                ('project_description', models.TextField(blank=True, null=True, verbose_name='Опис проєкту')),
                ('project_budget', models.CharField(blank=True, max_length=50, null=True, verbose_name='Бюджет')),
                ('project_deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Опрацьовано')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Нотатки')),
            ],
            options={
                'verbose_name': 'Контактний запит',
                'verbose_name_plural': 'Контактні запити',
                'ordering': ['-created_at'],
            },
        ),
    ]
