# Generated by Django 5.2 on 2025-05-16 20:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prometei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-ідентифікатор')),
                ('html_content', models.TextField(help_text='Повний HTML-код сторінки. Сюди будуть автоматично додані скрипти відстеження та ваші CSS/JS.', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='HTML-контент')),
                ('css_content', models.TextField(blank=True, help_text='Чистий CSS без тегів <style>.', verbose_name='CSS-стилі')),
                ('js_content', models.TextField(blank=True, help_text='Чистий JavaScript без тегів <script>.', verbose_name='JavaScript-код')),
                ('google_pixel_id', models.CharField(blank=True, max_length=50, verbose_name='Google Pixel ID (GTM ID)')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID')),
                ('meta_robots', models.CharField(default='noindex, nofollow', help_text='Директиви для пошукових роботів, наприклад, "noindex, nofollow".', max_length=50, verbose_name='Meta Robots')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Спеціальний лендінг',
                'verbose_name_plural': 'Спеціальні лендінги',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='prometei_la_created_fe1756_idx')],
            },
        ),
        migrations.CreateModel(
            name='LandingPageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адреса')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer', models.TextField(blank=True, null=True, verbose_name='Реферер')),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час візиту')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Час на сторінці (сек)')),
                ('path_data', models.JSONField(blank=True, default=dict, verbose_name='Дані активності (рух миші, скроли)')),
                ('meta_data', models.JSONField(blank=True, default=dict, verbose_name='Метадані відвідувача (екран, браузер)')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='prometei.landingpage')),
            ],
            options={
                'verbose_name': 'Візит лендінгу',
                'verbose_name_plural': 'Візити лендінгів',
                'ordering': ['-visit_time'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(blank=True, max_length=150, verbose_name='ID/Class елемента')),
                ('element_type', models.CharField(blank=True, max_length=50, verbose_name='Тип елемента (HTML Tag)')),
                ('interaction_type', models.CharField(choices=[('click', 'Клік'), ('submit', 'Відправка форми'), ('scroll_deep', 'Глибокий скрол'), ('view_element', 'Перегляд елемента')], default='click', max_length=20, verbose_name='Тип взаємодії')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час взаємодії')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='prometei.landingpagevisit')),
            ],
            options={
                'verbose_name': 'Взаємодія на лендінгу',
                'verbose_name_plural': 'Взаємодії на лендінгах',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='landingpagevisit',
            index=models.Index(fields=['visit_time'], name='prometei_la_visit_t_77670a_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpagevisit',
            index=models.Index(fields=['landing_page', 'visit_time'], name='prometei_la_landing_b6b7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpageinteraction',
            index=models.Index(fields=['visit', 'timestamp'], name='prometei_la_visit_i_0ba5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpageinteraction',
            index=models.Index(fields=['interaction_type'], name='prometei_la_interac_168c41_idx'),
        ),
    ]
