# Generated by Django 5.2 on 2025-05-16 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prometei', '0002_landingpage_landingpagevisit_landingpageinteraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва шаблону')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('html_template', models.TextField(help_text='HTML-код шаблону. Використовуйте {{змінна}} для позначення місць, які будуть замінені при створенні сторінки.', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='HTML-шаблон')),
                ('css_content', models.TextField(blank=True, help_text='Чистий CSS без тегів <style>.', verbose_name='CSS-стилі')),
                ('js_content', models.TextField(blank=True, help_text='Чистий JavaScript без тегів <script>.', verbose_name='JavaScript-код')),
                ('available_variables', models.JSONField(default=dict, help_text="Словник змінних, які можна використовувати в шаблоні. Формат: {'назва': 'опис'}", verbose_name='Доступні змінні')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Шаблон лендінгу',
                'verbose_name_plural': 'Шаблони лендінгів',
                'ordering': ['name'],
            },
        ),
    ]
