# Generated by Django 4.2.7 on 2025-06-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prometei', '0003_landingpagetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='request_type',
            field=models.CharField(choices=[('contact', 'Контактна форма'), ('builder', 'Конструктор сайту'), ('promin', 'Заявка Промінь'), ('dream_site', 'Сайт мрії')], default='contact', max_length=20, verbose_name='Тип запиту'),
        ),
    ]
