# Generated by Django 5.2 on 2025-06-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prometei', '0005_add_course_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='request_type',
            field=models.CharField(choices=[('contact', 'Контактна форма'), ('builder', 'Конструктор сайту'), ('promin', 'Заявка Промінь'), ('dream_site', 'Сайт мрії'), ('course', 'Заявка на курс')], default='contact', max_length=20, verbose_name='Тип запиту'),
        ),
    ]
