# Generated by Django 4.2.21 on 2025-05-27 13:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('client_name', models.CharField(max_length=255, verbose_name="Ім'я клієнта")),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клієнта')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума в USD')),
                ('exchange_rate_usd_to_uah', models.DecimalField(decimal_places=4, help_text='Поточний курс обміну долара до гривні (наприклад, 39.50)', max_digits=10, verbose_name='Курс USD/UAH')),
                ('final_amount_uah', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Автоматично розрахована сума до оплати в гривнях', max_digits=10, null=True, verbose_name='Кінцева сума до оплати в UAH')),
                ('description', models.TextField(verbose_name='Опис платежу (для клієнта)')),
                ('company_info', models.TextField(blank=True, default='PrometeyLabs — це українська ІТ-компанія, що спеціалізується на швидкій розробці вебпродуктів, автоматизації процесів, інтеграції ШІ та чат-ботів. Ми працюємо швидко, без зайвих витрат та з фокусом на якість.\n\nОсновні напрямки:\nРозробка сайтів та платформ\nAI-аватари, чат-боти, телеграм-боти\nE-commerce рішення\nФОП Дмитренко Софія Дмитрівна\nІПН: 3770706565\nФОП зареєстровано в Україні, платник єдиного податку 3 групи.', editable=False, verbose_name='Інформація про компанію')),
                ('payment_instructions', models.TextField(blank=True, default='<p><strong>Умови оплати</strong><br>\nОплата здійснюється на підставі наданих реквізитів або через інтегровані платіжні системи (Google Pay / Apple Pay). Клієнт погоджується з умовами надання послуг до моменту здійснення платежу.<br>\nПісля підтвердження оплати ви отримаєте відповідне повідомлення, а статус сторінки буде оновлено.</p>\n\n<p><strong>Договір</strong><br>\nУсі послуги надаються відповідно до публічного договору, який доступний для ознайомлення на сторінці перед оплатою. Оплата є підтвердженням вашої згоди з умовами договору.</p>\n\n<p><strong>Політика повернення коштів</strong><br>\nУ разі виникнення спірних питань, ви можете звернутись до нашої служби підтримки протягом 7 календарних днів з моменту оплати.<br>\nПовернення коштів можливе лише у випадках, коли послуга не була надана або не відповідає погодженим умовам договору.<br>\nЗаявки на повернення розглядаються індивідуально, у строк до 5 робочих днів.</p>\n\n<p><strong>Контакти для звернень</strong><br>\nЗ усіх питань, пов\'язаних з оплатою, прохання звертатися на електронну адресу: prometeylabs@gmail.com<br>\nабо в telegram <a href="https://t.me/PrometeyLabs" target="_blank" rel="noopener noreferrer">@PrometeyLabs</a></p>', editable=False, verbose_name='Інформація щодо оплати та повернення')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/%d/', verbose_name='Файл договору (PDF)')),
                ('status', models.CharField(choices=[('new', 'Нове (не відкрито)'), ('pending', 'Очікує оплати'), ('paid', 'Оплачено'), ('expired', 'Протерміновано'), ('deactivated', 'Деактивовано')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата створення в адмінці')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('duration_minutes', models.IntegerField(choices=[(30, '30 хвилин'), (60, '1 година'), (180, '3 години'), (540, '9 годин'), (900, '15 годин'), (1440, '1 день (24 години)'), (0, 'Без обмеження часу')], default=1440, help_text="Відлік починається з моменту першого відкриття посилання клієнтом. Оберіть 'Без обмеження часу' для безстрокового посилання.", verbose_name='Термін дії посилання')),
                ('first_opened_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Вперше відкрито')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Дійсне до')),
                ('monobank_invoice_id', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, verbose_name='ID інвойсу в monobank')),
                ('monobank_invoice_url', models.URLField(blank=True, editable=False, null=True, verbose_name='URL для оплати в monobank')),
                ('payment_processed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата і час обробки платежу')),
            ],
            options={
                'verbose_name': 'Платіжне посилання',
                'verbose_name_plural': 'Платіжні посилання',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payment_pay_status_f671b7_idx'), models.Index(fields=['expires_at'], name='payment_pay_expires_3bd40f_idx')],
            },
        ),
    ]
