# Generated by Django 4.2.21 on 2025-05-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('default_contract_file', models.FileField(blank=True, help_text='Цей договір буде автоматично доступний на всіх сторінках оплати', null=True, upload_to='contracts/default/', verbose_name='Договір за замовчуванням (PDF)')),
                ('contract_title', models.CharField(default='Публічний договір', help_text='Назва, яка буде відображатися біля посилання на договір', max_length=255, verbose_name='Назва договору')),
                ('contract_description', models.TextField(default='Усі послуги надаються відповідно до публічного договору, який доступний для ознайомлення на сторінці перед оплатою. Оплата є підтвердженням вашої згоди з умовами договору.', help_text='Текст, який буде відображатися біля посилання на договір', verbose_name='Опис договору')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Налаштування платіжної системи',
                'verbose_name_plural': 'Налаштування платіжної системи',
            },
        ),
    ]
